# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: harmon758/postgresql-action@v1
      with:
          postgresql version: '11'
          postgresql user: postgres
          postgresql password: postgres
          postgresql db: nest_words
    - run: yarn install
    - run: yarn run build
    - run: yarn test
      env:
        DATABASE_NAME: nest_words
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_PORT: 5432
        DATABASE_HOST: localhost
        JWT_SECRET: hyqxcqkmtnajvdyewsrbszjnvpedjwhh
        OXFORD_APP_ID: ${{ secrets.OXFORD_APP_ID }}
        OXFORD_APP_KEY: ${{ secrets.OXFORD_APP_KEY }}